footprint: [[-0.38, -0.25], [-0.38, 0.25], [0.3, 0.25], [0.3, -0.25]]

#plugins layers list
static_layer:
  enabled: true
  unknown_cost_value: -1
  lethal_cost_threshold: 100
  map_topic: /map
  first_map_only: false
  subscribe_to_updates: true
  track_unknown_space: true
  use_maximum: false
  trinary_costmap: false

obstacle_layer:
  enabled: true
  #Sensor management parameters
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    topic: /obstacle_scan
    sensor_frame: livox_frame
    data_type: PointCloud2
    min_obstacle_height: 0.0
    max_obstacle_height: 1.5
    clearing: true
    marking: true
  obstacle_range: 2.0
  raytrace_range: 3.0

  #ObstacleCostmapPlugin
  track_unknown_space: true

global_inflation_layer:
  enabled: true
  inflation_radius: 0.6
  cost_scaling_factor: 2.0

local_inflation_layer:
  enabled: true
  inflation_radius: 0.6 #0.15
  cost_scaling_factor: 5.0 #5.0
