local_costmap:
  #Coordinate frame and tf parameters
  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 2.0 #default:0.2

  #Rate parameters
  update_frequency: 5.0 #5.0
  publish_frequency: 5.0 #5.0

  #Map params
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05

  #robot model
  inscribed_radius: 0.35
  circumscribed_radius: 0.35

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}

