base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

controller_frequency: 5.0 #10.0
controller_patience: 15.0 #3.0 second
planner_frequency: 1.0 #3.0
planner_patience: 5.0 #3.0 second

conservative_reset_dist: 0.3 #3.0 meter
recovery_behavior_enabled: true
clearing_rotation_allowed: false
shutdown_costmaps: false
oscillation_timeout: 10 #0.0 sec
oscillation_distance: 0.5 #0.5 meter
max_planning_retries: -1.0 #-1
